Fix build workflow docs job failure
cryptography 39 is causing problems on Ubuntu 22.04 for Sphinx
autosummary:

* AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

Stop installing pdfminer.six which is causing cryptography to be
installed.