Avoid FileNotFoundError if FILENAME does not exist
  File ".../linkcheck/fileutil.py", line 110, in is_valid_config_source
    return os.path.isfile(filename) or stat.S_ISFIFO(os.stat(filename).st_mode)
                                                     ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory